core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("product/<slug>", views.ItemDetailView.as_view(), name="product"),
    path("order-summary/", views.OrderSummaryView.as_view(), name="order-summary"),
    path("checkout/", views.CheckoutView.as_view(), name="checkout"),
    path("payment/<payment_option>", views.PaymentView.as_view(), name="payment"),
    path("request-refund/", views.RequestRefundView.as_view(), name="request-refund"),    
    path("products/", views.products, name="products"),
    path("add-to-cart/<slug>", views.add_to_cart, name="add-to-cart"),
    path("add-coupon/", views.AddCouponView.as_view(), name="add-coupon"),
    path("remove-from-cart/<slug>", views.remove_from_cart, name="remove-from-cart"),
    path("remove-all-from-cart/<slug>", views.remove_all_from_cart, name="remove-all-from-cart"),
    path("account-login/", views.custom_login, name="account_login"),
    path("account-logout/", views.logout, name="account_logout"),
    path("account-signup/", views.signup, name="account_signup"),
    path("logout/", views.custom_logout, name="logout"),
]

djecommerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


app_name = "core"

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("accounts/", include("allauth.urls")),
    path("", include("core.urls", namespace="core")),
]

templates/accounts/login.html
{% extends "base.html" %}
{% load i18n %} 
{% load account socialaccount %} 
{% load crispy_forms_tags %}
{% block head_title %}
{% trans "Sign In" %} {% endblock %} {% block content %}
<main>
  <div class="container">
    <section class="mb-4">
      <div class="row wow fadeIn">
        <div class="col-6 offset-3">
          <h1>{% trans "Log In" %}</h1>

          {% get_providers as socialaccount_providers %} 
          {% if socialaccount_providers %}
          <p>
            {% blocktrans with site.name as site_name %}Please log in with one
            of your existing third party accounts. Or,
            <a href="{{ signup_url }}">sign up</a> for a {{ site_name }} account
            and log in below:{% endblocktrans %}
          </p>

          <div class="socialaccount_ballot">
            <ul class="socialaccount_providers">
              {% include "socialaccount/snippets/provider_list.html" with
              process="login" %}
            </ul>

            <div class="login-or">{% trans 'or' %}</div>
          </div>

          {% include "socialaccount/snippets/login_extra.html" %}

          {% else %}
          <p>
            {% blocktrans %}If you have not created an account yet, then please
            <a href="{{ signup_url }}">sign up</a> first.{% endblocktrans %}
          </p>
          {% endif %}

          <form
            class="login"
            method="POST"
            action="{% url 'core:account_login' %}"
          >
            {% csrf_token %} {{ form|crispy }} {% if redirect_field_value %}
            <input 
              type="hidden"
              name="{{ redirect_field_name }}"
              value="{{ redirect_field_value }}"
            />

            {% endif %}
            <a class="btn btn-default" href=""
              >{% trans "Forgot Password?" %}</a
            >
            <button class="btn btn-primary" type="submit">
              {% trans "Sign In" %}
            </button>
          </form>
        </div>
      </div>
    </section>
  </div>
</main>

{% endblock %}

templates/accounts/logout.html
{% extends "base.html" %}
{% load i18n %}

{% block head_title %}{% trans "Sign Out" %}{% endblock %}

{% block content %}
  <main>
    <div class="container">
      <section class="mb-4">
        <div class="row wow fadeIn">
          <div class='col-6 offset-3'>
            <h1>{% trans "Sign Out" %}</h1>
            <p>{% trans 'Are you sure you want to sign out?' %}</p>
            <form method="post" action="{% url 'core:logout' %}">
              {% csrf_token %}
              {% if redirect_field_value %}
              <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
              {% endif %}
              <button a href = "{% url 'core:logout' %}" class='btn btn-primary' type="submit">{% trans 'Sign Out' %}</button>
            </form>
          </div>
        </div>
      </section>
    </div>
  </main>
{% endblock %}

templates/accounts/signup.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Signup" %}{% endblock %}

{% block content %}
  <main>
    <div class="container">
      <section class="mb-4">
        <div class="row wow fadeIn">
          <div class='col-6 offset-3'>
            <h1>{% trans "Sign Up" %}</h1>
            <p>{% block container %}Already have an account? Then please <a href="{% url 'core:account_login' %}">log in</a>.{% endblock container %}</p>
            <form class="signup" id="signup_form" method="post" action="{% url 'core:account_signup' %}">
              {% csrf_token %}
              {{ form|crispy }}
              {% if redirect_field_value %}
              <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
              {% endif %}
              <button class='btn btn-primary' type="submit">{% trans "Sign Up" %} &raquo;</button>
            </form>
          </div>
        </div>
      </section>
    </div>
  </main>
{% endblock %}