core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("product/<slug>", views.ItemDetailView.as_view(), name="product"),
    path("order-summary/", views.OrderSummaryView.as_view(), name="order-summary"),
    path("checkout/", views.CheckoutView.as_view(), name="checkout"),
    path("payment/<payment_option>", views.PaymentView.as_view(), name="payment"),
    path("request-refund/", views.RequestRefundView.as_view(), name="request-refund"),    
    path("products/", views.products, name="products"),
    path("add-to-cart/<slug>", views.add_to_cart, name="add-to-cart"),
    path("add-coupon/", views.AddCouponView.as_view(), name="add-coupon"),
    path("remove-from-cart/<slug>", views.remove_from_cart, name="remove-from-cart"),
    path("remove-all-from-cart/<slug>", views.remove_all_from_cart, name="remove-all-from-cart"),
    path("account-login/", views.custom_login, name="account_login"),
    path("account-logout/", views.logout, name="account_logout"),
    path("account-signup/", views.signup, name="account_signup"),
    path("logout/", views.custom_logout, name="logout"),
]

djecommerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


app_name = "core"

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("accounts/", include("allauth.urls")),
    path("", include("core.urls", namespace="core")),
]

core/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django_countries.fields import CountryField


CATEGORY_CHOICES = (("S", "Shirt"), ("SW", "Sport wear"), ("OW", "Outwear"))
LABEL_CHOICES = (("P", "primary"), ("S", "secondary"), ("D", "danger"))
ADDRESS_CHOICES = (("B", "billing"), ("S", "shipping"))


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2, default="S")
    label = models.CharField(choices=LABEL_CHOICES, max_length=1, default="P")
    slug = models.SlugField()
    image_url = models.CharField(max_length=2083, default=False)
    description = models.TextField(default="") #models.ImageField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={"slug": self.slug})

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={"slug": self.slug})

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={"slug": self.slug})


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"
    
    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price
    
    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()
    
    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20,blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey('Address', related_name="shipping_address", on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey('Address', related_name="billing_address", on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey('Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)


    def __str__(self):
        return self.user.username
    
    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:    
            total -= self.coupon.amount
        return total
    

class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)
    
    def __str__(self):
        return self.user.username
    
    class Meta:
        verbose_name_plural = "Addresses"

class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.user.username
    

class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()
    
    def __str__(self):
        return self.code
    
class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()
    
    def __str__(self):
        return f"{self.pk}"
    

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %} {% endblock %}
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
    />
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet" />
    <style type="text/css">
      html,
      body,
      header,
      .carousel {
        height: 60vh;
      }

      @media (max-width: 740px) {
        html,
        body,
        header,
        .carousel {
          height: 100vh;
        }
      }

      @media (min-width: 800px) and (max-width: 850px) {
        html,
        body,
        header,
        .carousel {
          height: 100vh;
        }
      }
    </style>
  </head>
  {% include "navbar.html" %}

  <body>
    <div class="mt-5 pt-4">
      {% if messages %} {% for message in messages %}
      <div
        class="alert alert-{{ message.tags }} alert-dismissible fade show"
        role="alert"
      >
        {{ message }}
        <button
          type="button"
          class="close"
          data-dismiss="alert"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %} {% endif %}
    </div>

    {% block content %}{% endblock content %}
    {% block extra_body %}{% endblock extra_body %}
    {% include "footer.html" %}
    {% include "scripts.html" %}
    {% block extra_scripts %}{% endblock extra_scripts %}
  </body>
</html>

templates/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>

templates/home.html
{% extends "base.html" %} {% load static %} {% block content %}
  
  <body> 
  
    <main>
      <div class="container">
   
        <nav
          class="navbar navbar-expand-lg navbar-dark mt-3 mb-5 shadow p-2"
          style="background-color: #607d8b"
        >
          
          <div class="container-fluid">
       
            <a class="navbar-brand" href="#">Categories:</a>

        
            <button
              class="navbar-toggler"
              type="button"
              data-mdb-toggle="collapse"
              data-mdb-target="#navbarSupportedContent2"
              aria-controls="navbarSupportedContent2"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <i class="fas fa-bars"></i>
            </button>

            
            <div class="collapse navbar-collapse" id="navbarSupportedContent2">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                
                <li class="nav-item acitve">
                  <a class="nav-link text-white" href="#">All</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-white" href="#">Shirts</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-white" href="#">Sport wears</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-white" href="#">Outwears</a>
                </li>
              </ul>

              <!-- Search -->
              <form class="w-auto py-1" style="max-width: 12rem">
                <input
                  type="search"
                  class="form-control rounded-0"
                  placeholder="Search"
                  aria-label="Search"
                />
              </form>
            </div>
          </div>
          <!-- Container wrapper -->
        </nav>
        <!-- Navbar -->

        <!-- Products -->
        <section class="text-center mb-4">
          <div class="row wow fadeIn">
            {% for item in object_list %}

            <div class="col-lg-3 col-md-6 mb-4">
              <div class="card" style="height: 5=400px">
                <div class="view overlay">
                  <img
                    src="{{item.image_url}}"
                    style="height: 300px"
                    class="card-img-top"
                  />
                  <a href="{{ item.get_absolute_url }}">
                    <div class="mask rgba-white-slight"></div>
                  </a>
                </div>

                <div class="card-body text-center">
                  <a href="" class="grey-text">
                    <h5>{{ item.get_category_display }}</h5>
                  </a>

                  <h5>
                    <strong>
                      <a href="{{item.get_absolute_url}}" class="text-dark">
                        {{ item.title }} {% if item.discount_price %}
                        <span class="badge rounded-pill bg-danger">SALE</span>
                        {% else %}
                        <span class="badge rounded-pill btn-primary">NEW</span>
                        {% endif %}
                      </a>
                    </strong>
                  </h5>

                  <h4 class="font-weight-bold text-primary">
                    {% if item.discount_price %}
                    <strong>${{ item.discount_price }} </strong>
                    {% else %}
                    <strong>${{ item.price }} </strong>
                    {% endif %}
                  </h4>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </section>

        {% if is_paginated %}
        <nav class="d-flex justify-content-center wow fadeIn">
          <ul class="pagination pg-blue">

            {% if page_obj.has_previous %}
            <li class="page-item">
              <a
                class="page-link"
                href="?page={{ page_obj.previous_page_number }}"
                aria-label="Previous"
              >
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
              </a>
            </li>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
              {% if page_obj.number == num %}
              <li class="page-item active">
                <a class="page-link" href="?page={{ num }}">{{ num }} <span class="sr-only">(current)</span></a>
              </li>
              {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
              </li>
              {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <li class="page-item">
              <a
                class="page-link"
                href="?page={{ page_obj.next_page_number }}"
                aria-label="Next"
              >
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
              </a>
            </li>
            {% endif %}
          </ul>
        </nav>
        {% endif %}
      </div>
    </main>

    {% endblock content %}
  </body>
</html>

templates/item_list.html
{% extends "base.html" %} {% block content %}

<h2>Here is the list of items</h2>

{% for item in items %} {{item }} <br />
{% endfor %} {% endblock content %}

templates/navbar.html
{% load cart_template_tags %} {% load static %}
<nav
  class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar"
>
  <div class="container">
    <!-- Brand -->
    <a class="navbar-brand waves-effect" href="/">
      <strong class="blue-text">DJe-commerce</strong>
    </a>

    <ul class="navbar-nav me-auto mb-2 mb-lg-0"> 
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:checkout' %}">Checkout</a>
      </li>
    </ul>
    <!-- Collapse -->
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    
      <ul class="navbar-nav mr-auto">
      
      </ul>

      {% if request.user.is_authenticated %}
      <div class="d-flex justify-content-center align-items-center">
        <!-- Cart Icon -->
        <a class="nav-link me-3 position-relative" href="{% url 'core:order-summary' %}">
          <i
            class="fas fa-shopping-cart"
            style="font-size: 17px; color: blue"
          ></i>
          <!-- Badge -->
          <span
            class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger"
            style="
              font-size: 12px;
              padding: 3px 5px;
              transform: translate(-50%, -50%);
            "
          >
            {{ request.user|cart_item_count }}
          </span>
        </a>
      </div>
      <ul class="navbar-nav nav-flex-icons">
        <li class="nav-item">
          <a
            class="nav-link waves-effect"
            href="{% url 'core:account_logout' %}"
          >
            <span class="clearfix d-none d-sm-inline-block"> Logout </span>
          </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a
            class="nav-link waves-effect"
            href="{% url 'core:account_login' %}"
          >
            <span class="clearfix d-none d-sm-inline-block"> Login </span>
          </a>
        </li>
        <li class="nav-item">
          <a
            class="nav-link waves-effect"
            href="{% url 'core:account_signup' %}"
          >
            <span class="clearfix d-none d-sm-inline-block"> Signup </span>
          </a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
        <small class="text-muted">{{ order_item.item.description}}</small>
        </div>
        <span class="text-muted">${{ order_item.get_final_price }}</span>
    </li>
    {% endfor %}
    
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-${{ order.coupon.amount }}</span>
    </li>
    {% endif %} 
    <li class="list-group-item d-flex justify-content-between">
        <span>Total (USD)</span>
        <strong>${{ order.get_total }}
    </li>
    </ul>


    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}"  method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %} 

</div>

templates/order_summary.html
{% extends "base.html" %} {% block content %}
<main>
  <div class="container">
    <div class="table-responsive text-nowrap">
      <h2>Order Summary</h2>
      <table class="table" style="table-layout: fixed; width: 100%;">
        <thead>
          <tr>
            <th scope="col" style="width: 10%;">#</th>
            <th scope="col">Item title</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
            <th scope="col">Remove Item</th>
          </tr>
        </thead>
        <tbody>
          {% for order_item in object.items.all %}
          <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{ order_item.item.title }}</td>
            <td>
              {% if order_item.item.discount_price %}
              <del>{{order_item.item.price}}</del>
              ${{ order_item.item.discount_price }} {% else %}
              ${{order_item.item.price }} {% endif %}
            </td>

            <td>
                <a href="{% url 'core:remove-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2" ></i></a> 
                {{  order_item.quantity  }} 
                <a href="{% url 'core:add-to-cart' order_item.item.slug  %}"><i class="fas fa-plus ml-2"></i></a>
            </td>

            <td>
              {% if order_item.item.discount_price %}
              ${{order_item.get_total_discount_item_price }}
              <span class="badge badge-primary"
                >Saving ${{ order_item.get_amount_saved }}</span
              >
              {% else %} ${{ order_item.get_total_item_price }} {% endif %}
            </td>
            <td><a style="color:red" href="{% url 'core:remove-all-from-cart' order_item.item.slug %}"><i class="fas fa-trash"></i></a></td>
          </tr> 
          {% empty %}
          <tr>
            <td colspan="5"><b>Your cart is empty</b></td>
          </tr>
          <tr>
            <td colspan="6">
              <a
                style="float: right; margin-right: 5px"
                class="btn btn-primary"
                href="/"
                >Continue shopping</a
              >
            </td>
          </tr>
          {% endfor %} 
         
   
          {% if object.items.count > 0 %}
          {% if object.coupon %}
          <tr>
            <td colspan="5"></td>
            <td colspan="1"><b>COUPON: ${{ object.coupon.amount }}</b></td>
          </tr>
          {% endif %}
          <tr>
            <td colspan="5"></td>
            <td colspan="1"><b>TOTAL PRICE: ${{ object.get_total }}</b></td>
          </tr>
          <tr>
            <td colspan="6">
              <a
                style="float: right"
                class="btn btn-warning"
                href="{% url 'core:checkout' %}"
                >Proceed to checkout</a
              >
              <a
                style="float: right; margin-right: 5px"
                class="btn btn-primary"
                href="/"
                >Continue shopping</a
              >
            </td>
          </tr>
          {% endif %}
        </tbody>
      </table>
    </div>
  </div>
</main>

{% endblock content %}

templates/product.html
{% extends "base.html" %}
{% load cart_template_tags %}
{% block content %} {% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Meta tags -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Bootstrap CSS -->
    <link
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      rel="stylesheet"
    />

    <!-- MDB CSS -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.1/mdb.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
    />
    <!-- Your Custom CSS -->
    <link href="{% static 'styles.css' %}" rel="stylesheet" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />

    <title>Bootstrap</title>
  </head>
  <body>
    <!-- Navbar -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-white">
      <!-- Container wrapper -->
      <div class="container">
        <!-- Toggle button -->
        <button
          class="navbar-toggler"
          type="button"
          data-mdb-toggle="collapse"
          data-mdb-target="#navbarSupportedContent1"
          aria-controls="navbarSupportedContent1"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <i class="fas fa-bars"></i>
        </button>

        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent1">
          <!-- Navbar brand -->
          <a class="navbar-brand mt-2 mt-sm-0" href="{% url 'core:home' %}">
            DJe-commerce
          </a>
          <!-- Left links -->
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'core:home' %}">Home</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:checkout' %}">Checkout</a>
            </li>
        
          </ul>
          <!-- Left links -->
        </div>
        <!-- Collapsible wrapper -->

        <!-- Right elements -->
        <div class="d-flex align-items-center">
          <!-- Icon -->
          <a class="nav-link me-3" href="{% url 'core:order-summary' %}">
            <i class="fas fa-shopping-cart">  </i>
            <span class="badge rounded-pill badge-notification bg-danger"
              >{{ request.user|cart_item_count }}</span
            >
          </a>

        

        </div>

        
        <!-- Right elements -->
      </div>
      <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->

    <br /><br />
  </head>
    <main class="mt-5 pt-4">
      <div class="container dark-grey-text mt-5">
        <!--Grid row-->
        <div class="row wow fadeIn">
          <!--Grid column-->
          <div class="col-md-6 mb-4">
            <img
              src="{{item.image_url}}"
              style="width: 400px; height: 400px"
              class="img-fluid"
              alt=""
            />
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-md-6 mb-4">
            <!--Content-->
            <div class="p-4">
              <div class="mb-3">
                <a href="">
                  <span class="badge purple mr-1"
                    >{{ object.get_category_display }}</span
                  >
                </a>
                <a href="">
                  {% if object.discount_price %}
                  <span class="badge bg-danger">SALE</span>
                  {% else %}
                  <span class="badge btn-primary">NEW</span> 
                  {% endif %}
                </a>
              </div>

              <p class="lead">
                {% if object.discount_price %}
                <span class="mr-1">
                  <del>${{ object.price }}</del>
                </span>
                <span>${{ object.discount_price }}</span>
                {% else %}
                <span>${{ object.price }}</span>
                {% endif %}
              </p>

              <p class="lead font-weight-bold">Description</p>

              <p>{{ object.description }}</p>

              {% comment %} <form class="d-flex justify-content-left"> {% endcomment %}
                {% comment %} <!-- Default input -->
                <input
                  type="number"
                  value="1"
                  aria-label="Search"
                  class="form-control"
                  style="width: 100px"
                />
                <button class="btn btn-primary btn-md my-0 p" type="submit">
                  Add to cart
                  <i class="fas fa-shopping-cart ml-1"></i>
                </button>
              </form> {% endcomment %}

              <a
                href="{{ object.get_add_to_cart_url }}"
                class="btn btn-primary btn-md my-0 p"
              >
                Add to cart 
                <i class="fas fa-shopping-cart ml-1"></i>
              </a>
              <a
                href="{{ object.get_remove_from_cart_url }}"
                class="btn btn-danger btn-md my-0 p"
              >
                Remove from cart
              </a> 
            </div>
            <!--Content-->
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->

        <hr />

        <!--Grid row-->
        <div class="row d-flex justify-content-center wow fadeIn">
          <!--Grid column-->
          <div class="col-md-6 text-center">
            <h4 class="my-4 h4">Additional information</h4>

            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus
              suscipit modi sapiente illo soluta odit voluptates, quibusdam
              officia. Neque quibusdam quas a quis porro? Molestias illo neque
              eum in laborum.
            </p>
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->

        <!--Grid row-->
        <div class="row wow fadeIn">
          <!--Grid column-->
          <div class="col-lg-4 col-md-12 mb-4">
            <img
              src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg"
              class="img-fluid"
              alt=""
            />
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-lg-4 col-md-6 mb-4">
            <img
              src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg"
              class="img-fluid"
              alt=""
            />
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-lg-4 col-md-6 mb-4">
            <img
              src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg"
              class="img-fluid"
              alt=""
            />
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->
      </div>
    </main>

    {% endblock content %}
  </body>
</html>

templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}

templates/scripts.html
{% load static %}
  
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>